/**
 * Author：zhoushuanglong
 * Time：2017/7/27
 * Description：index constants
 */

// 登陆
export const LOGIN = 'login'

// 面包屑
export const BREADCRUMB = 'breadcrumb'
// 导航
export const NAVIGATION = 'navigation'

// 游戏列表
export const GAMELIST = 'game-list'

// 帖子管理
export const POST = {
    'ADD_DATA': 'ADD_POST_DATA',
    'ADD_QUERY': 'ADD_POST_QUERY',
    'EDIT_USER_INFO': 'ADD_POST_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_POST_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_POST_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_POST_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_POST_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_POST_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_POST_FILTER_DATA'
}

// 审核新闻
export const ARTICLEAUDIT = {
    'ADD_DATA': 'ADD_ARTICLEAUDIT_DATA',
    'ADD_QUERY': 'ADD_ARTICLEAUDIT_QUERY',
    'EDIT_USER_INFO': 'ADD_ARTICLEAUDIT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_ARTICLEAUDIT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_ARTICLEAUDIT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_ARTICLEAUDIT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_ARTICLEAUDIT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_ARTICLEAUDIT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_ARTICLEAUDIT_FILTER_DATA'
}

// ICO 管理
export const ICO = {
    'ADD_DATA': 'ADD_ICO_DATA',
    'ADD_QUERY': 'ADD_ICO_QUERY',
    'EDIT_USER_INFO': 'ADD_ICO_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_ICO_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_ICO_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_ICO_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_ICO_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_ICO_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_ICO_FILTER_DATA'
}

// 直播管理
export const LIVE = {
    'ADD_DATA': 'ADD_LIVE_DATA',
    'ADD_QUERY': 'ADD_LIVE_QUERY',
    'EDIT_USER_INFO': 'ADD_LIVE_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_LIVE_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_LIVE_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_LIVE_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_LIVE_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_LIVE_PAGE_DATA',
    'GET_ZCR_LIST': 'GET_ZCR_LIST',
    'GET_GUEST_LIST': 'GET_GUEST_LIST',
    'SET_FILTER_DATA': 'SET_LIVE_FILTER_DATA'
}

// 直播内容管理
export const LIVECONTENT = {
    'ADD_DATA': 'ADD_LIVECONTENT_DATA',
    'MORE_DATA': 'MORE_LIVECONTENT_DATA',
    'ADD_QUERY': 'ADD_LIVECONTENT_QUERY',
    'EDIT_USER_INFO': 'ADD_LIVECONTENT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_LIVECONTENT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_LIVECONTENT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_LIVECONTENT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_LIVECONTENT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_LIVECONTENT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_LIVECONTENT_FILTER_DATA',
    'INSERT_LIVE': 'INSERT_CONTENT_LIVE'
}

// 直播用户管理
export const LIVEUSER = {
    'ADD_DATA': 'ADD_LIVEUSER_DATA',
    'ADD_QUERY': 'ADD_LIVEUSER_QUERY',
    'EDIT_USER_INFO': 'ADD_LIVEUSER_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_LIVEUSER_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_LIVEUSER_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_LIVEUSER_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_LIVEUSER_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_LIVEUSER_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_LIVEUSER_FILTER_DATA'
}

// 专题内容管理
export const SPECIALTOPIC = {
    'ADD_DATA': 'ADD_SPECIALTOPIC_DATA',
    'MORE_DATA': 'MORE_SPECIALTOPIC_DATA',
    'ADD_QUERY': 'ADD_SPECIALTOPIC_QUERY',
    'EDIT_USER_INFO': 'ADD_SPECIALTOPIC_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_SPECIALTOPIC_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_SPECIALTOPIC_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_SPECIALTOPIC_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_SPECIALTOPIC_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_SPECIALTOPIC_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_SPECIALTOPIC_FILTER_DATA',
    'GET_TOP_NUM': 'GET_TOP_NUM'
}
// 专栏作者管理
export const COLUMNAUTHOR = {
    'ADD_DATA': 'ADD_COLUMNAUTHOR_DATA',
    'MORE_DATA': 'MORE_COLUMNAUTHOR_DATA',
    'ADD_QUERY': 'ADD_COLUMNAUTHOR_QUERY',
    'EDIT_USER_INFO': 'ADD_COLUMNAUTHOR_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_COLUMNAUTHOR_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_COLUMNAUTHOR_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_COLUMNAUTHOR_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_COLUMNAUTHOR_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_COLUMNAUTHOR_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_COLUMNAUTHOR_FILTER_DATA',
    'GET_TOP_NUM': 'GET_TOP_NUM'
}
// 新闻聚合管理
export const NEWSMERGE = {
    'ADD_DATA': 'ADD_NEWSMERGE_DATA',
    'MORE_DATA': 'MORE_NEWSMERGE_DATA',
    'ADD_QUERY': 'ADD_NEWSMERGE_QUERY',
    'EDIT_USER_INFO': 'ADD_NEWSMERGE_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_NEWSMERGE_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_NEWSMERGE_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_NEWSMERGE_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_NEWSMERGE_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_NEWSMERGE_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_NEWSMERGE_FILTER_DATA'
}

// 帖子管理
export const COMMENT = {
    'ADD_DATA': 'ADD_COMMENT_DATA',
    'ADD_QUERY': 'ADD_COMMENT_QUERY',
    'EDIT_USER_INFO': 'ADD_COMMENT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_COMMENT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_COMMENT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_COMMENT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_COMMENT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_COMMENT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_COMMENT_FILTER_DATA'
}

// 快讯管理
export const FLASH = {
    'ADD_DATA': 'ADD_FLASH_DATA',
    'ADD_QUERY': 'ADD_FLASH_QUERY',
    'EDIT_USER_INFO': 'ADD_FLASH_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_FLASH_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_FLASH_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_FLASH_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_FLASH_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_FLASH_PAGE_DATA'
}

// 发帖子用户管理
export const USERPOST = {
    'ADD_DATA': 'ADD_USERPOST_DATA',
    'ADD_QUERY': 'ADD_USERPOST_QUERY',
    'EDIT_USER_LIST_ITEM': 'EDIT_USER_LIST_ITEM',
    'EDIT_USER_POST_LIST_ITEM': 'EDIT_USER_POST_LIST_ITEM',
    'EDIT_COMMENT_LIST_ITEM': 'EDIT_COMMENT_LIST_ITEM',
    'DEL_USER_POST_LIST_ITEM': 'DEL_USER_POST_LIST_ITEM',
    'DEL_COMMENT_LIST_ITEM': 'DEL_COMMENT_LIST_ITEM',
    'SET_SEARCH_QUERY': 'SET_USER_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_USER_PAGE_DATA',
    'SET_POST_LIST_PAGE_DATA': 'SET_USER_POST_LIST_PAGE_DATA',
    'SET_COMMENT_LIST_PAGE_DATA': 'SET_USER_COMMENT_LIST_PAGE_DATA'
}

// 广告管理
export const AD = {
    'ADD_DATA': 'ADD_AD_DATA',
    'ADD_QUERY': 'ADD_AD_QUERY',
    'EDIT_USER_INFO': 'ADD_AD_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_AD_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_AD_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_AD_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_AD_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_AD_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_AD_FILTER_DATA'
}

// 身份认证审核
export const AUDIT = {
    'ADD_DATA': 'ADD_AUDIT_DATA',
    'ADD_QUERY': 'ADD_AUDIT_QUERY',
    'EDIT_USER_INFO': 'ADD_AUDIT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_AUDIT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_AUDIT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_AUDIT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_AUDIT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_AUDIT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_AUDIT_FILTER_DATA'
}

// 官方身份认证
export const OFFICIALAUDIT = {
    'ADD_DATA': 'ADD_OFFICIALAUDIT_DATA',
    'ADD_QUERY': 'ADD_OFFICIALAUDIT_QUERY',
    'EDIT_USER_INFO': 'ADD_OFFICIALAUDIT_USER_INFO',
    'EDIT_LIST_ITEM': 'EDIT_OFFICIALAUDIT_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_OFFICIALAUDIT_LIST_ITEM',
    'DEL_REPLY_LIST': 'DEL_OFFICIALAUDIT_REPLY_LIST',
    'SET_SEARCH_QUERY': 'SET_OFFICIALAUDIT_SEARCH_QUERY',
    'SET_PAGE_DATA': 'SET_OFFICIALAUDIT_PAGE_DATA',
    'SET_FILTER_DATA': 'SET_OFFICIALAUDIT_FILTER_DATA'
}

// 图片鉴别
export const IMGS = {
    'ADD_DATA': 'ADD_IMGS_DATA',
    'EDIT_SELECT_DATA': 'EDIT_IMGS_SELECT_DATA',
    'EDIT_LIST_ITEM': 'EDIT_IMGS_LIST_ITEM'
}

// 词条管理
export const LANGUAGE = {
    'ADD_DATA': 'ADD_LANGUAGE_DATA',
    'ADD_QUERY': 'ADD_LANGUAGE_QUERY',
    'EDIT_LIST_ITEM': 'EDIT_LANGUAGE_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_LANGUAGE_LIST_ITEM',
    'EDIT_REPEAT_LIST_ITEM': 'EDIT_LANGUAGE_REPEAT_LIST_ITEM',
    'SELECT_REPEAT_LIST_ITEM': 'SELECT_LANGUAGE_REPEAT_LIST_ITEM'
}

// 游戏初始化
export const INITGAME = {
    'ADD_DATA': 'ADD_INITGAME_DATA',
    'ADD_QUERY': 'ADD_INITGAME_QUERY',
    'EDIT_LIST_ITEM': 'EDIT_INITGAME_LIST_ITEM'
}

// 用户权限
export const AUTHORITY = {
    'ADD_DATA': 'ADD_AUTHORITY_DATA',
    'ADD_QUERY': 'ADD_AUTHORITY_QUERY',
    'EDIT_LIST_ITEM': 'EDIT_AUTHORITY_LIST_ITEM',
    'DEL_LIST_ITEM': 'DEL_AUTHORITY_LIST_ITEM'
}

// 选中数据
export const SELECTEDDATA = 'SELECTED_DATA'
